#!/usr/bin/env python3
"""Generate LaserJet II built-in glyph tables for Dreamulator."""

from __future__ import annotations

import json
import sys
from pathlib import Path


def c_array(name: str, data: bytes) -> str:
    lines = [f"static constexpr uint8_t {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("\t" + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(
            "Usage: tools/generate_ljii_fonts.py "
            "<../ljII/generated/analysis/ic32_ic15_builtin_glyph_payloads.json> "
            "<src/print/fontljii.cpp>",
            file=sys.stderr,
        )
        return 2

    source = Path(sys.argv[1])
    output = Path(sys.argv[2])
    doc = json.loads(source.read_text(encoding="utf-8"))

    data = bytearray()
    records = []
    glyphs = []
    for record in doc["records"]:
        record_index = len(records)
        first_glyph = len(glyphs)
        for glyph in record["glyphs"]:
            payload = bytes.fromhex(glyph["payload_hex"])
            offset = len(data)
            data.extend(payload)
            glyphs.append(
                (
                    record_index,
                    int(glyph["host_byte"]),
                    int(glyph["width"]),
                    int(glyph["x_offset"]),
                    int(glyph["y_offset"]),
                    int(glyph["rows"]),
                    int(glyph["render_span"]),
                    offset,
                    len(payload),
                )
            )
        records.append(
            (
                int(record["context_longword"]),
                first_glyph,
                len(glyphs) - first_glyph,
            )
        )

    out = []
    out.append("// Generated by tools/generate_ljii_fonts.py -- do not edit")
    out.append("// Source: " + str(source))
    out.append('#include "fontljii.h"')
    out.append("#include <algorithm>")
    out.append("")
    out.append("struct LjiiRecordEntry { uint32_t context; uint32_t first; uint16_t count; };")
    out.append("struct LjiiGlyphEntry {")
    out.append("\tuint8_t record; uint8_t host; uint8_t width; int8_t x_offset;")
    out.append("\tint8_t y_offset; uint8_t rows; uint8_t span; uint32_t offset; uint16_t len;")
    out.append("};")
    out.append("")
    out.append(c_array("ljii_glyph_data", bytes(data)))
    out.append("")
    out.append("static constexpr LjiiRecordEntry ljii_records[] = {")
    for context, first, count in records:
        out.append(f"\t{{ 0x{context:08x}u, {first}u, {count}u }},")
    out.append("};")
    out.append("")
    out.append("static constexpr LjiiGlyphEntry ljii_glyphs[] = {")
    for record, host, width, xoff, yoff, rows, span, offset, length in glyphs:
        out.append(
            f"\t{{ {record}u, 0x{host:02x}u, {width}u, {xoff}, {yoff}, "
            f"{rows}u, {span}u, {offset}u, {length}u }},"
        )
    out.append("};")
    out.append("")
    out.append("uint32_t default_ljii_context_for_pitch(float pitch_cpi, int symbol_set)")
    out.append("{")
    out.append("\tif (pitch_cpi > 14.0f) {")
    out.append("\t\tif (symbol_set == 0x0155) return 0x440946b4u;")
    out.append("\t\tif (symbol_set == 0x0175) return 0x44094b08u;")
    out.append("\t\tif (symbol_set == 0x000e) return 0x40094f5cu;")
    out.append("\t\treturn 0x400942e4u;")
    out.append("\t}")
    out.append("\tif (symbol_set == 0x0155) return 0x4408a37cu;")
    out.append("\tif (symbol_set == 0x0175) return 0x4408a7ccu;")
    out.append("\tif (symbol_set == 0x000e) return 0x4008ac1cu;")
    out.append("\treturn 0x40089fb0u;")
    out.append("}")
    out.append("")
    out.append("LjiiGlyphInfo get_ljii_glyph(uint32_t context_longword, uint8_t host_byte)")
    out.append("{")
    out.append("\tfor (const auto &record : ljii_records) {")
    out.append("\t\tif (record.context != context_longword) continue;")
    out.append("\t\tfor (uint32_t i = 0; i < record.count; i++) {")
    out.append("\t\t\tconst auto &glyph = ljii_glyphs[record.first + i];")
    out.append("\t\t\tif (glyph.host != host_byte) continue;")
    out.append("\t\t\treturn { true, glyph.width, glyph.x_offset, glyph.y_offset,")
    out.append("\t\t\t         glyph.rows, glyph.span, ljii_glyph_data + glyph.offset,")
    out.append("\t\t\t         glyph.len };")
    out.append("\t\t}")
    out.append("\t\tbreak;")
    out.append("\t}")
    out.append("\treturn {};")
    out.append("}")

    output.write_text("\n".join(out) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
